<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GymPackageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $packages = [
            [
                'type' => 'visit',
                'name' => 'Daily Pass',
                'category' => 'single',
                'max_members' => 1,
                'pt_sessions' => null,
                'price' => 65000,
                'discount' => 0,
                'normal_price' => 65000,
                'net_price' => null,
                'unrecommended_price' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2026-02-26 09:17:59',
                'updated_at' => '2026-03-28 17:14:50',
            ],
            [
                'type' => 'gym',
                'name' => 'Membership Weekly Pass',
                'category' => 'single',
                'max_members' => 1,
                'pt_sessions' => null,
                'price' => 129000,
                'discount' => 0,
                'normal_price' => 100000,
                'net_price' => null,
                'unrecommended_price' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2026-02-26 09:20:51',
                'updated_at' => '2026-03-28 17:16:41',
            ],
            [
                'type' => 'gym',
                'name' => 'Membership 1 Monthly Pass',
                'category' => 'single',
                'max_members' => 1,
                'pt_sessions' => null,
                'price' => 300000,
                'discount' => 0,
                'normal_price' => 300000,
                'net_price' => 250000,
                'unrecommended_price' => 220000,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2026-02-26 09:25:22',
                'updated_at' => '2026-03-28 17:17:28',
            ],
            [
                'type' => 'gym',
                'name' => 'Membership 2 Monthly Pass',
                'category' => 'single',
                'max_members' => 1,
                'pt_sessions' => null,
                'price' => 500000,
                'discount' => 0,
                'normal_price' => 500000,
                'net_price' => 350000,
                'unrecommended_price' => 330000,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2026-02-26 09:26:00',
                'updated_at' => '2026-03-28 17:35:57',
            ],
            [
                'type' => 'gym',
                'name' => 'Membership 3 Monthly Pass',
                'category' => 'single',
                'max_members' => 1,
                'pt_sessions' => null,
                'price' => 750000,
                'discount' => 0,
                'normal_price' => 750000,
                'net_price' => 500000,
                'unrecommended_price' => 400000,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2026-02-26 09:26:23',
                'updated_at' => '2026-03-28 17:36:33',
            ],
            [
                'type' => 'gym',
                'name' => 'Membership 6 Monthly Pass',
                'category' => 'single',
                'max_members' => 1,
                'pt_sessions' => null,
                'price' => 1500000,
                'discount' => 0,
                'normal_price' => 1500000,
                'net_price' => 700000,
                'unrecommended_price' => 650000,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2026-02-26 09:26:48',
                'updated_at' => '2026-03-28 17:37:00',
            ],
            [
                'type' => 'gym',
                'name' => 'Membership Yearly Pass',
                'category' => 'single',
                'max_members' => 1,
                'pt_sessions' => null,
                'price' => 2700000,
                'discount' => 0,
                'normal_price' => 2700000,
                'net_price' => 1200000,
                'unrecommended_price' => 1000000,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2026-02-26 09:27:07',
                'updated_at' => '2026-03-28 17:37:46',
            ],
            [
                'type' => 'pt',
                'name' => 'Personal Trainer Single 1 Session',
                'category' => 'single',
                'max_members' => 1,
                'pt_sessions' => 1,
                'price' => 200000,
                'discount' => 0,
                'normal_price' => 200000,
                'net_price' => null,
                'unrecommended_price' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2026-02-26 09:27:32',
                'updated_at' => '2026-03-28 17:38:33',
            ],
            [
                'type' => 'pt',
                'name' => 'Personal Trainer Single 5 Sessions',
                'category' => 'single',
                'max_members' => 1,
                'pt_sessions' => 5,
                'price' => 900000,
                'discount' => 0,
                'normal_price' => 900000,
                'net_price' => 750000,
                'unrecommended_price' => 600000,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2026-02-26 09:27:58',
                'updated_at' => '2026-03-28 17:39:29',
            ],
            [
                'type' => 'pt',
                'name' => 'Personal Trainer Single 10 Sessions',
                'category' => 'single',
                'max_members' => 1,
                'pt_sessions' => 10,
                'price' => 1600000,
                'discount' => 0,
                'normal_price' => 1600000,
                'net_price' => 1400000,
                'unrecommended_price' => 1100000,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2026-02-26 09:29:00',
                'updated_at' => '2026-03-28 17:41:12',
            ],
            [
                'type' => 'pt',
                'name' => 'Personal Trainer Single 20 Sessions',
                'category' => 'single',
                'max_members' => 1,
                'pt_sessions' => 20,
                'price' => 2800000,
                'discount' => 0,
                'normal_price' => 2800000,
                'net_price' => 2400000,
                'unrecommended_price' => 1900000,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2026-02-26 09:29:40',
                'updated_at' => '2026-03-28 17:41:47',
            ],
            [
                'type' => 'pt',
                'name' => 'Personal Trainer Single 30 Sessions',
                'category' => 'single',
                'max_members' => 1,
                'pt_sessions' => 30,
                'price' => 3900000,
                'discount' => 0,
                'normal_price' => 3900000,
                'net_price' => 3500000,
                'unrecommended_price' => 2900000,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2026-03-28 17:44:32',
                'updated_at' => '2026-03-28 17:45:06',
            ],
            [
                'type' => 'pt',
                'name' => 'Personal Trainer Couple 1 Session',
                'category' => 'couple',
                'max_members' => 2,
                'pt_sessions' => 1,
                'price' => 250000,
                'discount' => 0,
                'normal_price' => 250000,
                'net_price' => null,
                'unrecommended_price' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2026-03-28 17:50:50',
                'updated_at' => '2026-03-28 17:51:01',
            ],
            [
                'type' => 'pt',
                'name' => 'Personal Trainer Couple 5 Sessions',
                'category' => 'couple',
                'max_members' => 2,
                'pt_sessions' => 5,
                'price' => 1150000,
                'discount' => 0,
                'normal_price' => 1150000,
                'net_price' => 1000000,
                'unrecommended_price' => 900000,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2026-03-28 17:51:46',
                'updated_at' => '2026-03-28 17:51:59',
            ],
            [
                'type' => 'pt',
                'name' => 'Personal Trainer Couple 10 Sessions',
                'category' => 'couple',
                'max_members' => 2,
                'pt_sessions' => 10,
                'price' => 2100000,
                'discount' => 0,
                'normal_price' => 2100000,
                'net_price' => 1600000,
                'unrecommended_price' => 1500000,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2026-03-28 17:52:56',
                'updated_at' => '2026-03-28 17:52:56',
            ],
            [
                'type' => 'pt',
                'name' => 'Personal Trainer Couple 20 Sessions',
                'category' => 'couple',
                'max_members' => 2,
                'pt_sessions' => 20,
                'price' => 3800000,
                'discount' => 0,
                'normal_price' => 3800000,
                'net_price' => 3400000,
                'unrecommended_price' => 2900000,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2026-03-28 17:54:01',
                'updated_at' => '2026-03-28 17:54:01',
            ],
        ];

        DB::table('gym_packages')->insert($packages);
    }
}
